### ISSUE TITLE
Aspects missing texture

### ISSUE THREAD

**Issue by Buuz135** [Dyonovan/TCNodeTracker#1]
http://gyazo.com/5bfb5509648f22995ddb09e9896230b7
The arrow that marks to the node is missing too

**Comment by Dyonovan** [comment]
My bad. Forgot to include resources on GitHub. Fixed https://github.com/Dyonovan/TCNodeTracker/commit/8c03b086fb36779c9444e23dfc2f3f1a9c5d66bc
