### ISSUE TITLE
Cross dimension compatibility?

### ISSUE THREAD

**Issue by wizard1399** [Dyonovan/TCNodeTracker#10]
Was just wondering how your mod handles other dimensions?  There are nodes in all the dimensions and having a way to specify in the list which dimension the node is is would be good.  Being able to sort by dimension or aspect would be useful  as well.

**Comment by Dyonovan** [comment]
Check to make sure you are using version 1.0.1 as its already implemented.

https://github.com/Dyonovan/TCNodeTracker/issues/8
