### ISSUE TITLE
nodes lower in list dont mark correctly

### ISSUE THREAD

**Issue by Hazado** [Dyonovan/TCNodeTracker#11]
Using version tcnodetracker-1.7.10-1.0.1.jar, when I press the down arrow and then mark something that is lower in the list it takes me to a different node.

**Comment by Dyonovan** [comment]
Fixed in https://github.com/Dyonovan/TCNodeTracker/commit/616f3f1194930ab9d7943df9e740373f31780ba9

Released version 1.0.2
