### ISSUE TITLE
Error in console while loading world

### ISSUE THREAD

**Issue by crunkazcanbe** [Dyonovan/TCNodeTracker#13]
As the title says I get this error here http://pastebin.com/AR30YMKF in the console while loading the world . It appears multiple times .

**Comment by Dyonovan** [comment]
This should and will occur the very first time and anytime you run the program before scanning your first node.

The file doesn't get created until the first node is scanned and saved.

Is this causing any other issues or just a log thing?

Going to close for now. If it is causing issues somewhere, reopen and I will look into it.
