### ISSUE TITLE
Thaumic Horizon Auto Scanning Lens - Add to allow tracking

### ISSUE THREAD

**Issue by Cyrakrum** [Dyonovan/TCNodeTracker#15]
It appears that this mod isn't recording nodes in twilight forest. I've only scanned in the overworld and here but my twilight forest list appears to be empty.

**Comment by Dyonovan** [comment]
Can you send me your node.json file (pastebin or if its to big google drive or dropbox).

This will allow me to see if its in scanning or displaying.

**Comment by Cyrakrum** [comment]
I actually just realised the problem was me. My bad. Now I feel really dumb. Uhh the problem is that I'm using thaumic horizon's auto scanning lens. Once I took out the old thaumometer it started tracking.

**Comment by Dyonovan** [comment]
There is another item that can scan nodes?? Let me look into it and I can prob add it to the code to accept that.

**Comment by Lunatrius** [comment]
Moved to the new issue.

**Comment by Dyonovan** [comment]
This is a different and new issue. Moving. #16

Did you just created the new mystcraft age? and what happenes when you exit the game, reload, then look at the list?

**Comment by Dyonovan** [comment]
Tried to get a hold of the author to see if we can work something out but never got a response. Closing as unable to do
