### ISSUE TITLE
Dealing with new Mystcraft Dims

### ISSUE THREAD

**Issue by Dyonovan** [Dyonovan/TCNodeTracker#16]
Need to fix dealing with newly created mystcraft dims.

**Comment by Lunatrius** [comment]
``` json
[
  {
    "aspect": { "herba": 22, "ignis": 17, "terra": 19 },
    "type": "DARK",
    "dim": 0, "x": -717, "y": 73, "z": -5
  },
  {
    "aspect": { "tempestas": 20 },
    "type": "UNSTABLE",
    "dim": 0, "x": -695, "y": 67, "z": -281
  },
  {
    "aspect": { "ignis": 20, "aqua": 10, "terra": 22 },
    "type": "NORMAL",
    "dim": 0, "x": -828, "y": 64, "z": -330
  },
  {
    "aspect": { "herba": 36, "ignis": 17, "aqua": 21 },
    "type": "NORMAL",
    "dim": 0, "x": -549, "y": 64, "z": -184
  },
  {
    "aspect": { "aer": 1, "perditio": 1, "exanimis": 12, "instrumentum": 9, "ordo": 6 },
    "type": "DARK",
    "dim": 0, "x": -525, "y": 80, "z": -229
  },
  {
    "aspect": { "ignis": 27, "ordo": 55 },
    "type": "NORMAL",
    "dim": 0, "x": -489, "y": 77, "z": -222
  },
  {
    "aspect": { "terra": 50 },
    "type": "NORMAL",
    "dim": 0, "x": -894, "y": 71, "z": -335
  },
  {
    "aspect": { "perditio": 44, "ignis": 32 },
    "type": "NORMAL",
    "dim": 2, "x": 138, "y": 72, "z": -125
  }
]
```

The dimension 2 (Mystcraft dimension, named `Test (#2)`) does not show up on the dimension list. Scanned the node with a Thaumometer.

The dimension was just created. Am about to test what happens after a restart.

**Comment by Lunatrius** [comment]
Restarting the game (or even just the world) picks up the dimension.

Could most likely fix it by populating the dimension list when the GUI is opened.

**Comment by Dyonovan** [comment]
Yeup thats what i figured. I was trying to be processor friendly and only create the Dim list on connect, but I totally forgot about Mystcraft. Give me 30 mins and I should have a new version ready for release to fix it.

**Comment by Lunatrius** [comment]
Actually, there might be a better way. You could probably populate the list on an EntityJoinEvent or similar.

**Comment by Dyonovan** [comment]
its small enough code that just moving it to when gui opens shouldnt impact any performance.

**Comment by Dyonovan** [comment]
Available http://minecraft.curseforge.com/mc-mods/227328-thaumcraft-node-tracker/files/2228958

Let me know if it doesnt fix it.
