### ISSUE TITLE
Import from JourneyMap

### ISSUE THREAD

**Issue by mjlachman** [Dyonovan/TCNodeTracker#19]
I have a ton of waypoints spread throughout and was wondering if there was a way to easily import the nodes from JourneyMap? I see it's all json under the hood, are there attributes I can leave blank that will fill in when I actually go visit the node?

**Comment by Dyonovan** [comment]
If you just add the x,y,z,dim info. It will update the node info next time you scan it again

**Comment by mjlachman** [comment]
Thanks!
