### ISSUE TITLE
Add Node Type to List

### ISSUE THREAD

**Issue by EndermanParty** [Dyonovan/TCNodeTracker#2]
Does the mod show what type of node the node is? (as in sinister, tainted, pure, etc)

**Comment by Dyonovan** [comment]
The code to implement this is basically all ready included.. There is just a small issue I'm sorting out but it will be included.

**Comment by EndermanParty** [comment]
Thanks, I am happy to suggest more things; when I think of them of course

**Comment by Dyonovan** [comment]
Added https://github.com/Dyonovan/TCNodeTracker/commit/18a0ee4b7267e32ef98f1c0624211f2a72ef23b4

Will be in next release later today.
