### ISSUE TITLE
Could a node compass be possible?

### ISSUE THREAD

**Issue by timo103** [Dyonovan/TCNodeTracker#32]
Would it be possible to have a compass like the AE2 compass for meteors but for unscanned nodes?

It could be locked behind research so its not op right away.

**Comment by Dyonovan** [comment]
Its not possible in Node tracker due to the fact its a client side only mod. To do something like that I would have to make it a client/server mod which is beyond what I want this mod to be.

Its not a bad suggestion though. Maybe one of the other TC Addons?
