### ISSUE TITLE
Feature requests:All nodes at once, and beacon way-points.

### ISSUE THREAD

**Issue by MechWarrior99** [Dyonovan/TCNodeTracker#4]
First sorry if the is the wrong spot to put this :)

Okay now then the first feature request i have is that you at a button to your GUI that, when clicked will show you all of the nodes that you have. second at once. 

The second request is that you add some sort of icon/beacon thing so that once you select a nod in the GUI, a beacon or some sort of other icon will appear in world to show you where the nod is and once you have reached the nod the beacon/icon will go away. I believe that this feature will help players be able to find the nodes easier. Well pleas let me know what you think :D

**Comment by Dyonovan** [comment]
This is the correct place for suggestions :)

Next release will show all the nodes when you first open the gui list.

As for the 2nd suggestion, if you wear the goggles of revealing and press mark on the node, you will get an arrow on your screen pointing you to the node.

Thanks for the suggestions and keep them coming.
