### ISSUE TITLE
Helmets with Goggles of Revealing added don't show waypoint

### ISSUE THREAD

**Issue by MechWarrior99** [Dyonovan/TCNodeTracker#5]
I added this to the dw20 1.7.10 modpack on the FTB launcher, and i noticed that, when i combined the goggles of revealing with mana steal/elemental helmets the arrow did not show up that i could see. So if you cold find a way for that to work that would be cool :D

**Comment by Dyonovan** [comment]
Keep meaning to do that lol. Will add it for next release next day or 2.

**Comment by Dyonovan** [comment]
Fixed: https://github.com/Dyonovan/TCNodeTracker/commit/bc3a39dfbd8225dbe4e10e0e2938ad59d35a063f

In release 0.99-RC-2
