### ISSUE TITLE
Reference to System.exit(). FML doesn't like this

### ISSUE THREAD

**Issue by TomeWyrm** [Dyonovan/TCNodeTracker#6]
Was just perusing my Forge log and noticed this. Figured you should be made aware.

[Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[Client thread/WARN] [FML]: Offendor: com/dyonovan/tcnodetracker/lib/truetyper/TrueTypeFont.loadImage(Ljava/awt/image/BufferedImage;)I
[Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead

**Comment by Dyonovan** [comment]
Thanks for the heads up. Im actually removing the truetyper library anyways so should fix it.

**Comment by Dyonovan** [comment]
Removed: https://github.com/Dyonovan/TCNodeTracker/commit/e71bb9e594ff5160da7c340d3b6f518e3e1872ae
