### ISSUE TITLE
Filter list by current dimension

### ISSUE THREAD

**Issue by chrixian** [Dyonovan/TCNodeTracker#8]
It would be nice if by default the list only showed nodes in your current dimension, with the option to cycle through other dimensions or display all nodes at once (with a dimension column added to the table).

**Comment by Dyonovan** [comment]
On the list of things to do :)

**Comment by dronf** [comment]
Definitely!  As soon as I started mapping nodes in the nether, this mod stopped being useful, as 50% of the time i was going to an empty spot.  But, aside from that it's really well done :D

**Comment by Dyonovan** [comment]
added in https://github.com/Dyonovan/TCNodeTracker/commit/4116145aaad0e419f5809a2fc49ad6cbc59eac23.

Version 1.0.1 being released asap
