### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by EndermanParty** [Dyonovan/TCNodeTracker#9]
So I saw the change log and I noticed the part about it defaulting to (10 I believe) and then it shows arrows. For the arrows all I see is a purple square. If you need a pic, let me know and I shall take one for you. Also as a side note I am using Optifine.

**Comment by Dyonovan** [comment]
If you can give me a screen shot that would be great. As no one has had this issue, it might be Optifine which is known for causing issues.

Thanks for the offer, but I have someone that does my icons. (And yes, the crappy arrow is me till he does it )

**Comment by EndermanParty** [comment]
Oh.... XD by take a pic I meant a screen shot... I have no knowledge whatsoever when it comes to creating icons XD

**Comment by EndermanParty** [comment]
I am going to create a new instance with just thaumcraft and Thaumcraft Node tracker. I'll tell you what I find.

**Comment by Dyonovan** [comment]
Dyo Derp. I forgot to add the arrow texture to GitHub so it was never added to the build :(

Fixed in https://github.com/Dyonovan/TCNodeTracker/commit/aca02b4c152da411613b3fda430799521b35dcff and will be available later today or tomorrow for release.
